/**
 ******************************************************************************
 * @file    pinmap_hal.c
 * @authors Pablo Fuentes, Joseph Peñafiel
 * @version V1.0.1
 * @date    2019
 * @brief
 ******************************************************************************
 */

/* Includes ------------------------------------------------------------------*/
#include <stddef.h>
#include "stm32l0xx_ll_gpio.h"
#include "stm32l0xx_ll_tim.h"
#include "stm32l0xx_ll_adc.h"
#include "pinmap_hal.h"
#include "pinmap_impl.h"

#if defined(STM32L031F6)
#define TOTAL_PINS 15
#endif

#if defined(STM32L031K6) || defined(STM32L031K4)
#define TOTAL_PINS 25
#endif

#if defined(STM32L051C8)
#define TOTAL_PINS 37
#endif

#if !defined(STM32L031K6) && !defined(STM32L031K4) && !defined(STM32L031F6) && !defined(STM32L051C8)
#error "Se debe elegir entre STM32L031F6, STM32L031K6, STM32L031K4 o STM32L051C8"
#endif

/* Private typedef -----------------------------------------------------------*/

STM32_Pin_Info __PIN_MAP[TOTAL_PINS] =
    {
/*
 * GPIOx
 * pin (0-15)
 * adcCh
 * TIMx 
 * timCh
 * timAF
 * spiAF
 * i2cAF
 * uartAF
 */

#if defined(STM32L031F6)
        /* PA0 - 0*/ {GPIOA, LL_GPIO_PIN_0, LL_ADC_CHANNEL_0, TIM2, LL_TIM_CHANNEL_CH1, AF_2, AF_NONE, AF_NONE, AF_NONE},
        /* PA1 - 1*/ {GPIOA, LL_GPIO_PIN_1, LL_ADC_CHANNEL_1, TIM2, LL_TIM_CHANNEL_CH2, AF_2, AF_NONE, AF_NONE, AF_NONE},
        /* PA2 - 2*/ {GPIOA, LL_GPIO_PIN_2, LL_ADC_CHANNEL_2, TIM2, LL_TIM_CHANNEL_CH3, AF_2, AF_NONE, AF_NONE, AF_4},
        /* PA3 - 3*/ {GPIOA, LL_GPIO_PIN_3, LL_ADC_CHANNEL_3, TIM21, LL_TIM_CHANNEL_CH2, AF_2, AF_NONE, AF_NONE, AF_4},
        /* PA4 - 4*/ {GPIOA, LL_GPIO_PIN_4, LL_ADC_CHANNEL_4, NULL, TIM_CHANNEL_NONE, AF_NONE, AF_0, AF_NONE, AF_NONE},
        /* PA5 - 5*/ {GPIOA, LL_GPIO_PIN_5, LL_ADC_CHANNEL_5, TIM2, LL_TIM_CHANNEL_CH1, AF_5, AF_0, AF_NONE, AF_NONE},
        /* PA6 - 6*/ {GPIOA, LL_GPIO_PIN_6, LL_ADC_CHANNEL_6, TIM22, LL_TIM_CHANNEL_CH1, AF_5, AF_0, AF_NONE, AF_NONE},
        /* PA7 - 7*/ {GPIOA, LL_GPIO_PIN_7, LL_ADC_CHANNEL_7, TIM22, LL_TIM_CHANNEL_CH2, AF_5, AF_0, AF_NONE, AF_NONE},
        /* PA9 - 8*/ {GPIOA, LL_GPIO_PIN_9, ADC_CHANNEL_NONE, TIM22, LL_TIM_CHANNEL_CH1, AF_5, AF_NONE, AF_1, AF_4},
        /* PA10 - 9*/ {GPIOA, LL_GPIO_PIN_10, ADC_CHANNEL_NONE, TIM22, LL_TIM_CHANNEL_CH2, AF_5, AF_NONE, AF_1, AF_4},
        /* PA13 - 10*/ {GPIOA, LL_GPIO_PIN_13, ADC_CHANNEL_NONE, NULL, TIM_CHANNEL_NONE, AF_NONE, AF_NONE, AF_NONE, AF_NONE},
        /* PA14 - 11*/ {GPIOA, LL_GPIO_PIN_14, ADC_CHANNEL_NONE, NULL, TIM_CHANNEL_NONE, AF_NONE, AF_NONE, AF_NONE, AF_4},

        /* PB1 - 12*/ {GPIOB, LL_GPIO_PIN_1, LL_ADC_CHANNEL_9, TIM2, LL_TIM_CHANNEL_CH4, AF_5, AF_1, AF_NONE, AF_NONE},

        /* PC14 - 13*/ {GPIOC, LL_GPIO_PIN_14, ADC_CHANNEL_NONE, NULL, TIM_CHANNEL_NONE, AF_NONE, AF_NONE, AF_NONE, AF_NONE},
        /* PC15 - 14*/ {GPIOC, LL_GPIO_PIN_15, ADC_CHANNEL_NONE, NULL, TIM_CHANNEL_NONE, AF_NONE, AF_NONE, AF_NONE, AF_NONE},
#endif

#if defined(STM32L031K6) || defined(STM32L031K4)
        /* PA0 - 0*/ {GPIOA, LL_GPIO_PIN_0, LL_ADC_CHANNEL_0, TIM2, LL_TIM_CHANNEL_CH1, AF_2, AF_NONE, AF_NONE, AF_NONE},
        /* PA1 - 1*/ {GPIOA, LL_GPIO_PIN_1, LL_ADC_CHANNEL_1, TIM2, LL_TIM_CHANNEL_CH2, AF_2, AF_NONE, AF_NONE, AF_NONE},
        /* PA2 - 2*/ {GPIOA, LL_GPIO_PIN_2, LL_ADC_CHANNEL_2, TIM2, LL_TIM_CHANNEL_CH3, AF_2, AF_NONE, AF_NONE, AF_4},
        /* PA3 - 3*/ {GPIOA, LL_GPIO_PIN_3, LL_ADC_CHANNEL_3, TIM21, LL_TIM_CHANNEL_CH2, AF_2, AF_NONE, AF_NONE, AF_4},
        /* PA4 - 4*/ {GPIOA, LL_GPIO_PIN_4, LL_ADC_CHANNEL_4, NULL, TIM_CHANNEL_NONE, AF_NONE, AF_0, AF_NONE, AF_NONE},
        /* PA5 - 5*/ {GPIOA, LL_GPIO_PIN_5, LL_ADC_CHANNEL_5, TIM2, LL_TIM_CHANNEL_CH1, AF_5, AF_0, AF_NONE, AF_NONE},
        /* PA6 - 6*/ {GPIOA, LL_GPIO_PIN_6, LL_ADC_CHANNEL_6, TIM22, LL_TIM_CHANNEL_CH1, AF_5, AF_0, AF_NONE, AF_NONE},
        /* PA7 - 7*/ {GPIOA, LL_GPIO_PIN_7, LL_ADC_CHANNEL_7, TIM22, LL_TIM_CHANNEL_CH2, AF_5, AF_0, AF_NONE, AF_NONE},
        /* PA8 - 8*/ {GPIOA, LL_GPIO_PIN_8, ADC_CHANNEL_NONE, TIM2, LL_TIM_CHANNEL_CH1, AF_5, AF_NONE, AF_NONE, AF_NONE},
        /* PA9 - 9*/ {GPIOA, LL_GPIO_PIN_9, ADC_CHANNEL_NONE, TIM22, LL_TIM_CHANNEL_CH1, AF_5, AF_NONE, AF_1, AF_4},
        /* PA10 - 10*/ {GPIOA, LL_GPIO_PIN_10, ADC_CHANNEL_NONE, TIM22, LL_TIM_CHANNEL_CH2, AF_5, AF_NONE, AF_1, AF_4},
        /* PA11 - 11*/ {GPIOA, LL_GPIO_PIN_11, ADC_CHANNEL_NONE, TIM21, LL_TIM_CHANNEL_CH2, AF_5, AF_0, AF_NONE, AF_NONE},
        /* PA12 - 12*/ {GPIOA, LL_GPIO_PIN_12, ADC_CHANNEL_NONE, NULL, TIM_CHANNEL_NONE, AF_NONE, AF_0, AF_NONE, AF_NONE},
        /* PA13 - 13*/ {GPIOA, LL_GPIO_PIN_13, ADC_CHANNEL_NONE, NULL, TIM_CHANNEL_NONE, AF_NONE, AF_NONE, AF_NONE, AF_NONE},
        /* PA14 - 14*/ {GPIOA, LL_GPIO_PIN_14, ADC_CHANNEL_NONE, NULL, TIM_CHANNEL_NONE, AF_NONE, AF_NONE, AF_NONE, AF_4},
        /* PA15 - 15*/ {GPIOA, LL_GPIO_PIN_15, ADC_CHANNEL_NONE, TIM2, LL_TIM_CHANNEL_CH1, AF_5, AF_0, AF_NONE, AF_4},

        /* PB0 - 16*/ {GPIOB, LL_GPIO_PIN_0, LL_ADC_CHANNEL_8, TIM2, LL_TIM_CHANNEL_CH3, AF_5, AF_1, AF_NONE, AF_NONE},
        /* PB1 - 17*/ {GPIOB, LL_GPIO_PIN_1, LL_ADC_CHANNEL_9, TIM2, LL_TIM_CHANNEL_CH4, AF_5, AF_1, AF_NONE, AF_NONE},
        /* PB3 - 18*/ {GPIOB, LL_GPIO_PIN_3, ADC_CHANNEL_NONE, TIM2, LL_TIM_CHANNEL_CH2, AF_2, AF_0, AF_NONE, AF_NONE},
        /* PB4 - 19*/ {GPIOB, LL_GPIO_PIN_4, ADC_CHANNEL_NONE, TIM22, LL_TIM_CHANNEL_CH1, AF_4, AF_0, AF_NONE, AF_NONE},
        /* PB5 - 20*/ {GPIOB, LL_GPIO_PIN_5, ADC_CHANNEL_NONE, TIM22, LL_TIM_CHANNEL_CH2, AF_4, AF_0, AF_NONE, AF_NONE},
        /* PB6 - 21*/ {GPIOB, LL_GPIO_PIN_6, ADC_CHANNEL_NONE, TIM21, LL_TIM_CHANNEL_CH1, AF_5, AF_NONE, AF_1, AF_0},
        /* PB7 - 22*/ {GPIOB, LL_GPIO_PIN_7, ADC_CHANNEL_NONE, NULL, TIM_CHANNEL_NONE, AF_NONE, AF_NONE, AF_1, AF_0},

        /* PC14 - 23*/ {GPIOC, LL_GPIO_PIN_14, ADC_CHANNEL_NONE, NULL, TIM_CHANNEL_NONE, AF_NONE, AF_NONE, AF_NONE, AF_NONE},
        /* PC15 - 24*/ {GPIOC, LL_GPIO_PIN_15, ADC_CHANNEL_NONE, NULL, TIM_CHANNEL_NONE, AF_NONE, AF_NONE, AF_NONE, AF_NONE},
#endif

#if defined(STM32L051C8)
        /* PA0 - 0*/ {GPIOA, LL_GPIO_PIN_0, LL_ADC_CHANNEL_0, TIM2, LL_TIM_CHANNEL_CH1, AF_2, AF_NONE, AF_NONE, AF_NONE},
        /* PA1 - 1*/ {GPIOA, LL_GPIO_PIN_1, LL_ADC_CHANNEL_1, TIM2, LL_TIM_CHANNEL_CH2, AF_2, AF_NONE, AF_NONE, AF_NONE},
        /* PA2 - 2*/ {GPIOA, LL_GPIO_PIN_2, LL_ADC_CHANNEL_2, TIM2, LL_TIM_CHANNEL_CH3, AF_2, AF_NONE, AF_NONE, AF_4},
        /* PA3 - 3*/ {GPIOA, LL_GPIO_PIN_3, LL_ADC_CHANNEL_3, TIM2, LL_TIM_CHANNEL_CH4, AF_2, AF_NONE, AF_NONE, AF_4},
        /* PA4 - 4*/ {GPIOA, LL_GPIO_PIN_4, LL_ADC_CHANNEL_4, NULL, TIM_CHANNEL_NONE, AF_NONE, AF_0, AF_NONE, AF_NONE},
        /* PA5 - 5*/ {GPIOA, LL_GPIO_PIN_5, LL_ADC_CHANNEL_5, TIM2, LL_TIM_CHANNEL_CH1, AF_5, AF_0, AF_NONE, AF_NONE},
        /* PA6 - 6*/ {GPIOA, LL_GPIO_PIN_6, LL_ADC_CHANNEL_6, TIM22, LL_TIM_CHANNEL_CH1, AF_5, AF_0, AF_NONE, AF_NONE},
        /* PA7 - 7*/ {GPIOA, LL_GPIO_PIN_7, LL_ADC_CHANNEL_7, TIM22, LL_TIM_CHANNEL_CH2, AF_5, AF_0, AF_NONE, AF_NONE},
        /* PA8 - 8*/ {GPIOA, LL_GPIO_PIN_8, ADC_CHANNEL_NONE, NULL, TIM_CHANNEL_NONE, AF_NONE, AF_NONE, AF_NONE, AF_NONE},
        /* PA9 - 9*/ {GPIOA, LL_GPIO_PIN_9, ADC_CHANNEL_NONE, NULL, TIM_CHANNEL_NONE, AF_NONE, AF_NONE, AF_NONE, AF_4},
        /* PA10 - 10*/ {GPIOA, LL_GPIO_PIN_10, ADC_CHANNEL_NONE, NULL, TIM_CHANNEL_NONE, AF_NONE, AF_NONE, AF_NONE, AF_4},
        /* PA11 - 11*/ {GPIOA, LL_GPIO_PIN_11, ADC_CHANNEL_NONE, NULL, TIM_CHANNEL_NONE, AF_NONE, AF_0, AF_NONE, AF_NONE},
        /* PA12 - 12*/ {GPIOA, LL_GPIO_PIN_12, ADC_CHANNEL_NONE, NULL, TIM_CHANNEL_NONE, AF_NONE, AF_0, AF_NONE, AF_NONE},
        /* PA13 - 13*/ {GPIOA, LL_GPIO_PIN_13, ADC_CHANNEL_NONE, NULL, TIM_CHANNEL_NONE, AF_NONE, AF_NONE, AF_NONE, AF_NONE},
        /* PA14 - 14*/ {GPIOA, LL_GPIO_PIN_14, ADC_CHANNEL_NONE, NULL, TIM_CHANNEL_NONE, AF_NONE, AF_NONE, AF_NONE, AF_4},
        /* PA15 - 15*/ {GPIOA, LL_GPIO_PIN_15, ADC_CHANNEL_NONE, TIM2, LL_TIM_CHANNEL_CH1, AF_5, AF_0, AF_NONE, AF_4},

        /* PB0 - 16*/ {GPIOB, LL_GPIO_PIN_0, LL_ADC_CHANNEL_8, NULL, TIM_CHANNEL_NONE, AF_NONE, AF_NONE, AF_NONE, AF_NONE},
        /* PB1 - 17*/ {GPIOB, LL_GPIO_PIN_1, LL_ADC_CHANNEL_9, NULL, TIM_CHANNEL_NONE, AF_NONE, AF_NONE, AF_NONE, AF_NONE},
        /* PB2 - 18*/ {GPIOB, LL_GPIO_PIN_2, ADC_CHANNEL_NONE, NULL, TIM_CHANNEL_NONE, AF_NONE, AF_NONE, AF_NONE, AF_NONE},
        /* PB3 - 19*/ {GPIOB, LL_GPIO_PIN_3, ADC_CHANNEL_NONE, TIM2, LL_TIM_CHANNEL_CH2, AF_2, AF_0, AF_NONE, AF_NONE},
        /* PB4 - 20*/ {GPIOB, LL_GPIO_PIN_4, ADC_CHANNEL_NONE, TIM22, LL_TIM_CHANNEL_CH1, AF_4, AF_0, AF_NONE, AF_NONE},
        /* PB5 - 21*/ {GPIOB, LL_GPIO_PIN_5, ADC_CHANNEL_NONE, TIM22, LL_TIM_CHANNEL_CH2, AF_4, AF_0, AF_NONE, AF_NONE},
        /* PB6 - 22*/ {GPIOB, LL_GPIO_PIN_6, ADC_CHANNEL_NONE, NULL, TIM_CHANNEL_NONE, AF_NONE, AF_NONE, AF_1, AF_0},
        /* PB7 - 23*/ {GPIOB, LL_GPIO_PIN_7, ADC_CHANNEL_NONE, NULL, TIM_CHANNEL_NONE, AF_NONE, AF_NONE, AF_1, AF_0},
        /* PB8 - 24*/ {GPIOB, LL_GPIO_PIN_8, ADC_CHANNEL_NONE, NULL, TIM_CHANNEL_NONE, AF_NONE, AF_NONE, AF_4, AF_NONE},
        /* PB9 - 25*/ {GPIOB, LL_GPIO_PIN_9, ADC_CHANNEL_NONE, NULL, TIM_CHANNEL_NONE, AF_NONE, AF_5, AF_4, AF_NONE},
        /* PB10 - 26*/ {GPIOB, LL_GPIO_PIN_10, ADC_CHANNEL_NONE, TIM2, LL_TIM_CHANNEL_CH3, AF_2, AF_5, AF_6, AF_NONE},
        /* PB11 - 27*/ {GPIOB, LL_GPIO_PIN_11, ADC_CHANNEL_NONE, TIM2, LL_TIM_CHANNEL_CH4, AF_2, AF_NONE, AF_6, AF_NONE},
        /* PB12 - 28*/ {GPIOB, LL_GPIO_PIN_12, ADC_CHANNEL_NONE, NULL, TIM_CHANNEL_NONE, AF_NONE, AF_0, AF_NONE, AF_NONE},
        /* PB13 - 29*/ {GPIOB, LL_GPIO_PIN_13, ADC_CHANNEL_NONE, TIM21, LL_TIM_CHANNEL_CH1, AF_6, AF_0, AF5, AF_NONE},
        /* PB14 - 30*/ {GPIOB, LL_GPIO_PIN_14, ADC_CHANNEL_NONE, TIM21, LL_TIM_CHANNEL_CH2, AF_6, AF_0, AF_5, AF_NONE},
        /* PB15 - 31*/ {GPIOB, LL_GPIO_PIN_15, ADC_CHANNEL_NONE, NULL, TIM_CHANNEL_NONE, AF_NONE, AF_0, AF_NONE, AF_NONE},

        /* PC13 - 32*/ {GPIOC, LL_GPIO_PIN_13, ADC_CHANNEL_NONE, NULL, TIM_CHANNEL_NONE, AF_NONE, AF_NONE, AF_NONE, AF_NONE},
        /* PC14 - 33*/ {GPIOC, LL_GPIO_PIN_14, ADC_CHANNEL_NONE, NULL, TIM_CHANNEL_NONE, AF_NONE, AF_NONE, AF_NONE, AF_NONE},
        /* PC15 - 34*/ {GPIOC, LL_GPIO_PIN_15, ADC_CHANNEL_NONE, NULL, TIM_CHANNEL_NONE, AF_NONE, AF_NONE, AF_NONE, AF_NONE},

        /* PH0 - 35*/ {GPIOH, LL_GPIO_PIN_0, ADC_CHANNEL_NONE, NULL, TIM_CHANNEL_NONE, AF_NONE, AF_NONE, AF_NONE, AF_NONE},
        /* PH1 - 36*/ {GPIOH, LL_GPIO_PIN_1, ADC_CHANNEL_NONE, NULL, TIM_CHANNEL_NONE, AF_NONE, AF_NONE, AF_NONE, AF_NONE},
#endif
};

STM32_Pin_Info *HAL_Pin_Map()
{
        return __PIN_MAP;
}
